apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: expresscart
  name: expresscart
spec:
  ports:
  - name: "1111"
    port: 1111
    targetPort: 1111
  selector:
    io.kompose.service: expresscart
status:
  loadBalancer: {}
